version: "2"
run:
  timeout: 10m

linters:
  default: none
  enable:
    - asciicheck
    - bidichk
    - durationcheck
    - exhaustive
    - goconst
    - govet
    - ineffassign
    - misspell
    - nilerr
    - revive
    - staticcheck
    - tparallel
    - unconvert
    - unparam
    - unused
    - usestdlibvars
    - usetesting
  exclusions:
    presets:
      - comments
formatters:
  enable:
    - gofmt
    - goimports

