language: go
go:
  - 1.9.x
sudo: false
install:
  - go get -v github.com/alecthomas/gometalinter
  - gometalinter --install
script:
  - export PATH=$PATH:$HOME/gopath/bin
  - test -z "$(gometalinter --vendor --disable-all
    --enable=gofmt
    --enable=golint
    --enable=vet
    --enable=gosimple
    --enable=unconvert
    --deadline=10m ./... | tee /dev/stderr)"
