name: Build and Test
on: [push, pull_request]
permissions:
  contents: read

jobs:
  build:
    name: Go CI
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go: ["1.21", "1.22"]
    steps:
      - name: Set up Go
        uses: actions/setup-go@93397bea11091df50f3d7e59dc26a7711a8bcfbe #v4.1.0
        with:
          go-version: ${{ matrix.go }}
      - name: Check out source
        uses: actions/checkout@8ade135a41bc03ea155e62e844d188df1ea18608 #v4.1.0
      - name: Install Linters
        run: "curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.54.2"
      - name: Build
        run: go build ./...
      - name: Test
        run: ./run_tests.sh
